apiVersion: batch/v1
kind: Job
metadata:
  name: tp2-ml-job
  namespace: julianedutra
spec:
  template:
    spec:
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: tp2-pvc
      containers:
        - name: ml-job-container
          image: julianeagrd/tp2-ml-service:0.2
          volumeMounts:
            - name: model-storage
              mountPath: /app/model
      restartPolicy: Never
