apiVersion: v1
kind: Service
metadata:
  name: tp2-api-service
  namespace: julianedutra
spec:
  type: ClusterIP
  selector:
    app: tp2-api
  ports:
    - protocol: TCP
      port: 50016
      targetPort: 5000
